#集群版eureka的配置
server:
  port: 8762
spring:
  application:
    name: eureka-server02
  profiles:
    active: peer2
eureka:
  instance:
    hostname: peer2
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://peer1:8761/eureka/ #另一个eureka服务器的地址,如果有多个服务器,中间用逗号隔开
