server:
  port: 8765
spring:
  application:
    name: hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
turbine: #配置融合面板功能,融合哪些应用程序
  app-config: hystrix-ribbon,hystrix-feign
  cluster-name-expression: new String("default")
  combine-host-port: true