#服务的提供者,是eureka-server的客户端....
server:
  port: 8765
spring:
  application:
    name: ribbon-server-consumer02
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#修改默认的配置,禁止ribbon从eureka服务注册列表中读取服务信息,自己维护一个服务列表信息
ribbon:
  eureka:
    enabled: false

#自定义一个服务注册列表信息
customServer:
  ribbon: #ribbon实现负载均衡,是从服务列表中选择某一个服务器来处理请求.
    listOfServers: baidu.com,google.com

